title: Vincent Kuhlmann
name: Vincent Kuhlmann
description: A little website where I put things

minima:
  skin: classic

theme: minima
url: "http://vkuhlmann.github.io"

author: Vincent Kuhlmann
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.html
  - testpage.md
