title: Vincent Kuhlmann
name: Vincent Kuhlmann
description: >
  My own little place, inching forward each time I put a bit of time in it.
  Some day it will become something.

show_excerpts: false

highlighter: none

minima:
  skin: classic
  social_links:
    github: vkuhlmann
    linkedin: vincentkuhlmann

theme: minima
url: "http://vkuhlmann.github.io"

author: Vincent Kuhlmann
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - projects.html


