title: Vincent Kuhlmann
name: Vincent Kuhlmann
description: >
  My own little place, inching forward each time I put a bit of time in it.
  One day it will become something.

blogtitle: Vincent's blog

markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true

minima:
  skin: classic
  social_links:
    github: vkuhlmann
    linkedin: vincentkuhlmann

theme: minima
url: "http://vkuhlmann.github.io"

author: Vincent Kuhlmann

show_excerpts: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - projects.html

disqus:
  shortname: vkuhlmann

